# Dockerfile.backend
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the Prisma schema file explicitly
COPY prisma ./prisma

# Generate Prisma Client
RUN npx prisma generate

# Copy the entire application code
COPY . .

# Expose the backend port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
